data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    name: 'DLHLP'                         # Specify corpus
    path: '/data/storage/harry/test_env/DLHLP' #'pth/to/librispeech'
    # path: '/workspace/data/wTIMIT'         #'pth/to/librispeech'
    dev_split: ['dev']
    test_split: ['test']
    bucketing: False
    batch_size: 1
src:
  config: '/data/storage/harry/End-to-end-ASR-Pytorch/config/dlhlp_asr.yaml'
  ckpt: '/data/storage/harry/test_env/dlhlp_ckpt/hw1_best_att_dev.pth'

decode:
  beam_size: 5
  min_len_ratio: 0.01
  max_len_ratio: 0.30
  lm_path: '/data/storage/harry/test_env/dlhlp_ckpt/hw1_best_ppx.pth'
  lm_config: 'config/dlhlp_lm.yaml'
  lm_weight: 0.7
  ctc_weight: 0
